version: "3"


volumes: 
   db-data: 

services:
    web:
      image: ritmehra/reactweb:v1
      ports:
        - 3001:3000
      depends_on:
        - app
        
    app: 
      image: ritmehra/devicemanager:v2
      ports: 
        - 5000:8090
      depends_on: 
        - database
 
    database: 
      image: mysql
      volumes:
        - "db-data:/var/lib/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=mysecret
        - MYSQL_DATABASE=mydb
        - MYSQL_USER=devops
        - MYSQL_PASSWORD=dsfws
      ports:
        - 3307:3306      
   
    